baseURL = "https://aetherwave.co"
languageCode = "en-us"
title = "AetherWave Research Portal"

[params]
  description = "Quantum Analysis of Thargoid Signal Patterns"
  author = "Cmdr Pattern State & EC"
  mainSections = ["logs"]
  enableThemeToggle = true
  respectDNT = true

[params.pagination]
  logsPerPage = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true

[menu]
  [[menu.main]]
    name = "Logs"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Guides"
    url = "/guides/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[markup]
  [markup.highlight]
    style = "monokai"
  [markup.goldmark.renderer]
    unsafe = true  # Allow HTML in markdown

[build]
  writeStats = true

[module]
  [[module.mounts]]
    source = "assets/fonts"
    target = "static/fonts"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "assets/js"
    target = "assets/js"

[build.processing]
  css = true
  js = true

[imaging]
  quality = 85
  resampleFilter = "Lanczos"
  anchor = "Smart"
  
[security.funcs]
  getenv = ['^HUGO_']